@startuml
class DisplayUpdater
class Monitoring
class Scheduler
abstract class AbstractMotor
class CenterMotor
class LeftMotor
class RightMotor
class ColorSensor
class GyroSensor
class UltrasonicMotor
class GrabBottle3
interface ImplementMachine
interface ImplementUtil
abstract class AbstractUtil
class Arm
class Backward
class BackwardWithColor
class Forward
class ForwardWithColor
class ForwardWithSonar
class Turn
class TurnWithGyro2
+class leJOS{
Scheduler
Arm
Forward
ForwardWithColor
ForwardWithSonar
Backward
BackwardWithColor
TurnWithGyro2
GrabBottle3
SearchGyro
float MaxSpeed
main()
menu()
stop()
run()
runTest()
correctArm()
setOperationMode()
initGyro()
}

@enduml