@startuml

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

class leJOS{
Scheduler
Arm
Forward
ForwardWithColor
ForwardWithSonar
Backward
BackwardWithColor
TurnWithGyro2
GrabBottle3
SearchGyro
float MaxSpeed
main()
menu()
stop()
run()
runTest()
correctArm()
setOperationMode()
initGyro()
}

@enduml